File.stream!("./01/1.txt")
|> Stream.map(fn x -> x |> String.trim() |> String.to_integer() end)
|> Enum.chunk_every(3, 1, :discard)
|> Enum.map(&Enum.sum/1)
|> Enum.chunk_every(2, 1, :discard)
|> Enum.count(fn [x, y] -> x < y end)
|> IO.puts()
